# Generated by Django 3.1.5 on 2021-03-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210303_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paidAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderItems', to='store.order'),
        ),
    ]
