# Generated by Django 3.1.5 on 2021-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210122_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
