# Generated by Django 3.1.5 on 2021-01-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
